<div id="instructions">
  <span class="instrTitle">Gorimaki Instructions</span><br /><br /><br />
  The objective of Gorimaki is to get your horse (<img
  class="instrImg" src="player.gif" />) to the goal (<img
  class="instrImg" src="goal.gif" />), using whatever bricks (<img
  class="instrImg" src="images/full_brk_db.gif" />&nbsp;<img
  class="instrImg" src="images/lhml_brk_db.gif" />&nbsp;<img
  class="instrImg" src="images/lhrl_brk_db.gif" />&nbsp;<img
  class="instrImg" src="images/llmh_brk_db.gif" />&nbsp;<img
  class="instrImg" src="images/llrh_brk_db.gif" />&nbsp;<img
  class="instrImg" src="images/mhrl_brk_db.gif" />&nbsp;<img
  class="instrImg" src="images/mlrh_brk_db.gif" />) provided.<br /><br />

  Your horse moves at regular intervals (<img
  class="instrImg" src="instr_time.gif" />), and can jump a specified number of
  times (<img class="instrImg" src="instr_jumps.gif" />). Jumps are useful for
  overcoming flat bricks (<img
  class="instrImg" src="images/full_brk_db.gif" />&nbsp;<img
  class="instrImg" src="images/full_brk_dg.gif" />&nbsp;<img
  class="instrImg" src="images/full_brk_do.gif" />&nbsp;<img
  class="instrImg" src="images/full_brk_dr.gif" />&nbsp;<img
  class="instrImg" src="images/full_brk_lg.gif" />&nbsp;<img
  class="instrImg" src="images/full_brk_lp.gif" />&nbsp;<img
  class="instrImg" src="images/full_brk_ly.gif" />), but can only overcome a 
  brick one level higher than the current level (<img
  class="instrImg" src="instr_nojump.gif" />). If you don't create a
  desirable adjacent brick (<img
  class="instrImg" src="instr_des.gif" />&nbsp;<img
  class="instrImg" src="instr_undes.gif" />) for your horse in time,
  though, it will lose one jump. If there is no desirable adjacent brick at
  the time limit and jumps are depleted, you lose the game.

  <div id="instrDone">
    <form action="mainGame.php" method="POST">
      <input class="sInput" type="submit" value="PLAY!" /><br />
    </form>
  </div>
</div>


